# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gprs.ui'
#
# Created: Tue Mar  3 14:02:47 2015
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_gprs(object):
    def setupUi(self, gprs):
        gprs.setObjectName("gprs")
        gprs.resize(903, 588)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        gprs.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(gprs)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.split = QtWidgets.QSplitter(self.centralwidget)
        self.split.setOrientation(QtCore.Qt.Vertical)
        self.split.setObjectName("split")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.split)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.field = QtWidgets.QTreeWidget(self.horizontalLayoutWidget)
        self.field.setAnimated(True)
        self.field.setObjectName("field")
        self.horizontalLayout_2.addWidget(self.field)
        self.wells = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.wells.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.wells.setAlternatingRowColors(True)
        self.wells.setObjectName("wells")
        self.wells.setColumnCount(12)
        self.wells.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.wells.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.wells.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.wells.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.wells.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.wells.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.wells.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.wells.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.wells.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.wells.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.wells.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.wells.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.wells.setHorizontalHeaderItem(11, item)
        self.wells.horizontalHeader().setDefaultSectionSize(80)
        self.wells.horizontalHeader().setMinimumSectionSize(12)
        self.wells.verticalHeader().setVisible(False)
        self.wells.verticalHeader().setDefaultSectionSize(24)
        self.wells.verticalHeader().setMinimumSectionSize(12)
        self.horizontalLayout_2.addWidget(self.wells)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.alert = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.alert.setObjectName("alert")
        self.verticalLayout.addWidget(self.alert)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 15)
        self.horizontalLayout_2.setStretch(1, 70)
        self.horizontalLayout_2.setStretch(2, 15)
        self.frame = QtWidgets.QWidget(self.split)
        self.frame.setObjectName("frame")
        self.verticalLayout_2.addWidget(self.split)
        self.date = QtWidgets.QDateEdit(self.centralwidget)
        self.date.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.date.setCalendarPopup(True)
        self.date.setObjectName("date")
        self.verticalLayout_2.addWidget(self.date)
        self.lblDate = QtWidgets.QLabel(self.centralwidget)
        self.lblDate.setObjectName("lblDate")
        self.verticalLayout_2.addWidget(self.lblDate)
        self.lblLogo = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lblLogo.setFont(font)
        self.lblLogo.setStyleSheet("color: rgb(255, 0, 0);")
        self.lblLogo.setObjectName("lblLogo")
        self.verticalLayout_2.addWidget(self.lblLogo)
        gprs.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(gprs)
        self.statusBar.setObjectName("statusBar")
        gprs.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(gprs)
        self.toolBar.setIconSize(QtCore.QSize(64, 69))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        gprs.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionWebMail = QtWidgets.QAction(gprs)
        self.actionWebMail.setIcon(icon)
        self.actionWebMail.setObjectName("actionWebMail")
        self.actionSample = QtWidgets.QAction(gprs)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/logo/sample.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSample.setIcon(icon1)
        self.actionSample.setObjectName("actionSample")
        self.actionReport = QtWidgets.QAction(gprs)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/logo/report.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReport.setIcon(icon2)
        self.actionReport.setObjectName("actionReport")
        self.actionConfig = QtWidgets.QAction(gprs)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/logo/config.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfig.setIcon(icon3)
        self.actionConfig.setObjectName("actionConfig")
        self.actionExit = QtWidgets.QAction(gprs)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/logo/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setMenuRole(QtWidgets.QAction.QuitRole)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtWidgets.QAction(gprs)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/logo/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon5)
        self.actionHelp.setObjectName("actionHelp")
        self.toolBar.addAction(self.actionWebMail)
        self.toolBar.addAction(self.actionSample)
        self.toolBar.addAction(self.actionReport)
        self.toolBar.addAction(self.actionConfig)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHelp)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(gprs)
        self.date.dateChanged['QDate'].connect(gprs.on_field_date_changed)
        self.field.itemClicked['QTreeWidgetItem*','int'].connect(gprs.on_field_date_changed)
        self.actionConfig.triggered.connect(gprs.on_btnConfig)
        self.actionSample.triggered.connect(gprs.on_btnMail)
        self.actionReport.triggered.connect(gprs.on_btnReport)
        self.actionExit.triggered.connect(gprs.close)
        self.actionHelp.triggered.connect(gprs.on_btnHelp)
        self.actionWebMail.triggered.connect(gprs.on_webmail)
        QtCore.QMetaObject.connectSlotsByName(gprs)

    def retranslateUi(self, gprs):
        _translate = QtCore.QCoreApplication.translate
        gprs.setWindowTitle(_translate("gprs", "阴极保护监控系统 － 普元科技"))
        self.field.headerItem().setText(0, _translate("gprs", "作业区"))
        self.wells.setSortingEnabled(True)
        item = self.wells.horizontalHeaderItem(0)
        item.setText(_translate("gprs", "序号"))
        item = self.wells.horizontalHeaderItem(1)
        item.setText(_translate("gprs", "井组"))
        item = self.wells.horizontalHeaderItem(2)
        item.setText(_translate("gprs", "日期时间"))
        item = self.wells.horizontalHeaderItem(3)
        item.setText(_translate("gprs", "总电压(V)"))
        item = self.wells.horizontalHeaderItem(4)
        item.setText(_translate("gprs", "总电流(A)"))
        item = self.wells.horizontalHeaderItem(5)
        item.setText(_translate("gprs", "回路电阻(Ω)"))
        item = self.wells.horizontalHeaderItem(6)
        item.setText(_translate("gprs", "电流1(A)"))
        item = self.wells.horizontalHeaderItem(7)
        item.setText(_translate("gprs", "电流2(A)"))
        item = self.wells.horizontalHeaderItem(8)
        item.setText(_translate("gprs", "电流3(A)"))
        item = self.wells.horizontalHeaderItem(9)
        item.setText(_translate("gprs", "电流4(A)"))
        item = self.wells.horizontalHeaderItem(10)
        item.setText(_translate("gprs", "电流5(A)"))
        item = self.wells.horizontalHeaderItem(11)
        item.setText(_translate("gprs", "电流6(A)"))
        self.label_4.setText(_translate("gprs", "状态"))
        self.date.setDisplayFormat(_translate("gprs", "yyyy/MM"))
        self.lblDate.setText(_translate("gprs", "日期月份"))
        self.lblLogo.setText(_translate("gprs", "xx油田第三采油厂阴极保护监控系统"))
        self.actionWebMail.setText(_translate("gprs", "邮箱网页"))
        self.actionWebMail.setToolTip(_translate("gprs", "邮箱网页"))
        self.actionSample.setText(_translate("gprs", "数据采集"))
        self.actionSample.setToolTip(_translate("gprs", "数据采集"))
        self.actionReport.setText(_translate("gprs", "报表输出"))
        self.actionReport.setToolTip(_translate("gprs", "报表输出"))
        self.actionConfig.setText(_translate("gprs", "配置"))
        self.actionConfig.setToolTip(_translate("gprs", "配置"))
        self.actionExit.setText(_translate("gprs", "退出"))
        self.actionExit.setToolTip(_translate("gprs", "退出"))
        self.actionHelp.setText(_translate("gprs", "帮助"))
        self.actionHelp.setToolTip(_translate("gprs", "帮助"))

import res_rc
